extends:
    - airbnb

rules:


env:
    mocha   : true
    browser : true
    node    : true
    es6     : true

parserOptions:
    ecmaVersion: 7
    sourceType: "module"
    ecmaFeatures:
        jsx: true

parser: babel-eslint
