extends:
    - airbnb

rules:
    #
    # DISABLED RULES
    #
    react/jsx-filename-extension : 0 # Arbitrary in a react app
    import/prefer-default-export : 0 # Needlessly limiting
    import/no-named-as-default   : 0 # No clue why this is a thing
    global-require               : 0 # Limiting
    no-restricted-syntax         : 0 # Super arbitrary stuff, like no loops

    #
    # WARNINGS
    #
    react/prefer-stateless-function : 1

env:
    mocha   : true
    browser : true
    node    : true
    es6     : true

parserOptions:
    ecmaVersion: 7
    sourceType: "module"
    ecmaFeatures:
        jsx: true

parser: babel-eslint
