extends:
    - airbnb

rules:
    #
    # DISABLED RULES
    #

    # Allows ForIn
    no-restricted-syntax:
      - error
      #- ForInStatement
      - LabeledStatement
      - WithStatement

    guard-for-in     : 0 # For the above rule
    global-require   : 0 # Limiting
    arrow-body-style : 0 # Doesn't let you have single statement block functions

    #
    # DISABLE BECAUSE OF ERRORS
    #
    generator-star-spacing : 0 # This produces an error on async/await
    require-yield          : 0 # This produces an error on async/await

    #
    # WARNINGS
    #
    react/prefer-stateless-function : 1
    import/prefer-default-export    : 1 # Limits multi-export files when they aren't populated

env:
    mocha   : true
    browser : true
    node    : true
    es6     : true

parserOptions:
    ecmaVersion: 8
    sourceType: "module"
    ecmaFeatures:
        jsx: true

parser: babel-eslint
