extends:
    - airbnb

rules:
    #
    # DISABLED RULES
    #
    import/prefer-default-export : 0 # Needlessly limiting
    global-require               : 0 # Limiting
    no-restricted-syntax         : 0 # Super arbitrary stuff, like no loops

    #
    # DISABLE BECAUSE OF ERRORS
    #
    generator-star-spacing : 0 # This produces an error on async/await
    require-yield          : 0 # This produces an error on async/await

    #
    # WARNINGS
    #
    react/prefer-stateless-function : 1

env:
    mocha   : true
    browser : true
    node    : true
    es6     : true

parserOptions:
    ecmaVersion: 8
    sourceType: "module"
    ecmaFeatures:
        jsx: true

parser: babel-eslint
